notifications:
  irc:
    channels: "chat.freenode.net#firedrake"
    skip_join: true
    on_success: change
    on_failure: always
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} | %{build_url}"
language: python
python:
  - "2.6"
  - "2.7"
env:
  global:
    - C_INCLUDE_PATH=/usr/lib/openmpi/include
    - PETSC_CONFIGURE_OPTIONS="--download-ctetgen --download-triangle --download-chaco"
virtualenv:
  system_site_packages: true
# command to install dependencies
before_install:
  - sudo add-apt-repository -y ppa:cython-dev/master-ppa
  - sudo apt-get update -qq
  - "sudo apt-get install -qq build-essential python-dev git-core mercurial \
    cmake cmake-curses-gui libmed1 gmsh python-pip swig libhdf5-openmpi-dev \
    libopenmpi-dev openmpi-bin libblas-dev liblapack-dev gfortran \
    triangle-bin cython"
  - pip install -r requirements-minimal.txt
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install argparse ordereddict; fi
install: "python setup.py develop"
# command to run tests
script:
  - "flake8"
  - "py.test test --backend=sequential -v --tb=native"
  - "py.test test --backend=openmp -v --tb=native"
